<?php 
/**
 * implements hook_menu
 */
function matt_menu() {
  $items['matt'] = array(
    'title' => "Matt's Page",
    'page callback' => "show_matt_page",
    'access arguments' => array('access content'),
    'file' => 'includes/matt.matt_page.inc',
    'type' => MENU_CALLBACK
  );

  return $items;
}

function matt_help() {
  $output = ''; //declare your output variable
  $output = '<p>'. t("Displays help content of matt module") .'</p>';

  return $output;
} // function matt_help